### ISSUE TITLE
Unable to resolve module `crypto` react-native

### ISSUE THREAD

**Issue by ease-space** [brix/crypto-js#311]
Unable to resolve module `crypto` react-native v4.0.0

**Comment by camin-mccluskey** [comment]
Try [this](https://github.com/uuidjs/uuid#getrandomvalues-not-supported)

Essentially add 
`import 'react-native-get-random-values';`

**before** your import of crypto-js

**Comment by RnbWd** [comment]
this library does work with react-native prior to v4.0, so v3.x works.

**Comment by entronad** [comment]
If the issues caused by secure radom of crypto-js 4.0 bother you, such as too large bundle, unavalible in React Native... Maybe you can try [crypto-es](https://www.npmjs.com/package/crypto-es) .

We merged all updates of crypto-js 4.0 except the secure radom.

**Comment by stonebinox** [comment]
> this

@camin-mccluskey unfortunately, this didn't work for me. I still see the same error.

**Comment by vincicat** [comment]
crypto-js now works on RN 0.64, see https://github.com/brix/crypto-js/pull/259#issuecomment-799973769 for detail
